"""matkit backend for [pygRASPA](https://github.com/tdpham2/pygRASPA).

pygRASPA runs gRASPA Monte Carlo adsorption simulations with ML
interatomic potentials (FAIRChem eSEN/UMA/AllScAIP, MACE-Polar, Allegro).
This module produces simulation directories ready to launch with
``pygraspa run`` / ``pygraspa run-auto`` on a GPU machine. matkit itself
does not import pygRASPA at setup time — it only writes input files and a
small ``run.py`` that invokes pygRASPA when executed.

Mirrors the API of :mod:`matkit.graspa.graspa` so the two backends are
interchangeable apart from the ML-specific keyword arguments.
"""

from __future__ import annotations

import json
import shutil
from concurrent.futures import ThreadPoolExecutor
from itertools import product
from pathlib import Path

from ase.io import read as ase_read

from matkit.graspa.graspa import generate_component_blocks
from matkit.utils.cif import sanitize_cif_stem
from matkit.utils.template import copy_template, render_template
from matkit.utils.unitcell_calculator import calculate_cell_size

VALID_MODES = ("run", "run-auto")


def _render_run_py(
    *,
    mode: str,
    model_path: str,
    model_type: str,
    task: str | None,
    E_comps: list[float],
    save_poscar: bool,
    log_file: str = "output.log",
    checkpoint_file: str = "checkpoint.json",
    stop_flag: str = "STOP_FLAG",
) -> str:
    """Return the contents of the per-simulation ``run.py`` launcher."""
    if mode not in VALID_MODES:
        raise ValueError(f"mode must be one of {VALID_MODES}, got {mode!r}")
    task_repr = repr(task) if task is None else repr(task)
    ecomps_repr = "[" + ", ".join(repr(float(e)) for e in E_comps) + "]"

    header = (
        '"""Auto-generated by matkit.pygraspa.\n\n'
        "Run with `python run.py` (single-process) or wrap in"
        " your scheduler.\nFor run-auto mode, touch STOP_FLAG"
        ' to checkpoint and exit gracefully.\n"""\n\n'
        "from pygRASPA.utils import read_pseudo_atoms\n"
    )

    common_kwargs = (
        f"    model_path={model_path!r},\n"
        f"    model_type={model_type!r},\n"
        f"    task={task_repr},\n"
        f'    simulation_input="simulation.input",\n'
        f"    E_comps={ecomps_repr},\n"
        f"    save_trial_poscar={bool(save_poscar)!r},\n"
        f'    type_index_to_label=read_pseudo_atoms("pseudo_atoms.def"),\n'
    )

    if mode == "run":
        body = (
            "from pygRASPA.main import run\n\n"
            "run(\n"
            f"{common_kwargs}"
            f'    log_file_path="{log_file}",\n'
            ")\n"
        )
    else:  # run-auto
        body = (
            "from pygRASPA.auto.main import run_auto\n\n"
            "run_auto(\n"
            f"{common_kwargs}"
            f'    log_file="{log_file}",\n'
            f'    checkpoint_file="{checkpoint_file}",\n'
            f'    stop_flag="{stop_flag}",\n'
            ")\n"
        )

    return header + body


def setup_simulation(
    cif: str,
    outpath: str,
    adsorbates: list[dict],
    *,
    model_path: str,
    model_type: str,
    E_comps: list[float],
    task: str | None = None,
    mode: str = "run-auto",
    save_poscar: bool = False,
    temperature: float = 298.0,
    pressure: float = 1e5,
    cutoff: float = 12.8,
    n_cycle: int = 1000,
    template_dir: str = "template",
    cell_size: list[int] | None = None,
) -> bool:
    """Set up a pygRASPA (ML-potential GCMC) simulation directory.

    Writes the standard gRASPA input files plus a ``run.py`` launcher that
    invokes ``pygRASPA.main.run`` (``mode='run'``) or
    ``pygRASPA.auto.main.run_auto`` (``mode='run-auto'``) at run time.

    Args:
        cif: Path to the input CIF structure file.
        outpath: Directory to write simulation files to.
        adsorbates: List of adsorbate dicts with at least ``MoleculeName``.
            Length must equal ``len(E_comps)``.
        model_path: Path to the ML model checkpoint (``.pt`` or deployed
            NequIP bundle).
        model_type: Backend identifier; one of pygRASPA's ``MODEL_TYPES``
            (e.g. ``FAIRChem-esen``, ``FAIRChem-uma``, ``mace_polar``).
        E_comps: Pre-computed ML energy of each isolated rigid adsorbate
            molecule, in eV. One entry per adsorbate.
        task: Task name required by FAIRChem-uma / FAIRChem-AllScAIP
            backends. Ignored otherwise.
        mode: ``'run'`` for plain ML MC, ``'run-auto'`` for checkpointed
            cluster-friendly run.
        save_poscar: Pass through to pygRASPA's ``save_trial_poscar``.
        temperature: Simulation temperature in Kelvin.
        pressure: Simulation pressure in Pascals.
        cutoff: Van der Waals cutoff radius in Angstrom.
        n_cycle: Number of Monte Carlo cycles.
        template_dir: Template subdirectory under ``files/``.
        cell_size: Pre-computed unit cell dimensions ``[uc_x, uc_y, uc_z]``.
            If provided, skips re-reading the CIF.

    Returns:
        ``True`` on success.

    Raises:
        FileNotFoundError: If the CIF file does not exist.
        ValueError: If ``len(adsorbates) != len(E_comps)``, or mode is
            invalid, or the FAIRChem task is missing when required.
    """
    if len(adsorbates) != len(E_comps):
        raise ValueError(
            f"adsorbates ({len(adsorbates)}) and E_comps ({len(E_comps)}) "
            "must have the same length"
        )
    if model_type in ("FAIRChem-uma", "FAIRChem-AllScAIP") and not task:
        raise ValueError(f"task is required when model_type is '{model_type}'")

    outdir = Path(outpath)
    cifpath = Path(cif)
    if not cifpath.exists():
        raise FileNotFoundError(f"CIF file does not exist: {cif}")
    safe_stem = sanitize_cif_stem(cifpath.stem)

    template_path = Path(__file__).parent / "files" / template_dir
    copy_template(template_path, outdir)
    shutil.copy(cifpath, outdir / f"{safe_stem}.cif")

    if cell_size is not None:
        uc_x, uc_y, uc_z = cell_size
    else:
        atoms = ase_read(cifpath)
        uc_x, uc_y, uc_z = calculate_cell_size(atoms)

    input_path = outdir / "simulation.input"
    render_template(
        input_path,
        {
            "NCYCLE": str(n_cycle),
            "TEMPERATURE": str(temperature),
            "PRESSURE": str(pressure),
            "CUTOFF": str(cutoff),
            "CIFFILE": safe_stem,
            "UC_X": str(uc_x),
            "UC_Y": str(uc_y),
            "UC_Z": str(uc_z),
        },
    )

    content = input_path.read_text()
    if "__COMPONENTS__" in content:
        component_block = generate_component_blocks(adsorbates)
        content = content.replace("__COMPONENTS__", component_block)
        input_path.write_text(content)

    (outdir / "run.py").write_text(
        _render_run_py(
            mode=mode,
            model_path=model_path,
            model_type=model_type,
            task=task,
            E_comps=E_comps,
            save_poscar=save_poscar,
        )
    )

    return True


def _setup_single_cif(
    cif: Path,
    out_path: Path,
    adsorbates: list[dict],
    temperatures: list[float],
    pressures: list[float],
    cutoff: float,
    n_cycle: int,
    template_dir: str,
    model_path: str,
    model_type: str,
    E_comps: list[float],
    task: str | None,
    mode: str,
    save_poscar: bool,
) -> list[dict]:
    """Set up all T x P pygRASPA simulations for one CIF file."""
    atoms = ase_read(cif)
    cell_size = calculate_cell_size(atoms)
    safe_stem = sanitize_cif_stem(cif.stem)

    entries = []
    for temp, pres in product(temperatures, pressures):
        sim_dir = out_path / safe_stem / f"T{temp}_P{pres:g}"
        setup_simulation(
            cif=str(cif),
            outpath=str(sim_dir),
            adsorbates=adsorbates,
            model_path=model_path,
            model_type=model_type,
            E_comps=E_comps,
            task=task,
            mode=mode,
            save_poscar=save_poscar,
            temperature=temp,
            pressure=pres,
            cutoff=cutoff,
            n_cycle=n_cycle,
            template_dir=template_dir,
            cell_size=cell_size,
        )
        entry = {
            "sim_dir": str(sim_dir),
            "cif": cif.name,
            "temperature": temp,
            "pressure": pres,
            "adsorbates": [ad["MoleculeName"] for ad in adsorbates],
            "model_path": model_path,
            "model_type": model_type,
            "mode": mode,
        }
        if safe_stem != cif.stem:
            entry["original_cif_stem"] = cif.stem
            entry["safe_cif_stem"] = safe_stem
        entries.append(entry)
    return entries


def setup_batch(
    cif_dir: str,
    outpath: str,
    adsorbates: list[dict],
    *,
    model_path: str,
    model_type: str,
    E_comps: list[float],
    temperatures: list[float],
    pressures: list[float],
    task: str | None = None,
    mode: str = "run-auto",
    save_poscar: bool = False,
    cutoff: float = 12.8,
    n_cycle: int = 1000,
    template_dir: str = "template",
    max_workers: int | None = None,
) -> list[dict]:
    """Set up pygRASPA simulations for all CIF x T x P combinations.

    Mirrors :func:`matkit.graspa.graspa.setup_batch`. Writes a
    ``simulations.jsonl`` manifest and (if any CIFs were renamed)
    a ``cif_mapping.json``.

    See :func:`setup_simulation` for argument semantics.
    """
    cif_path = Path(cif_dir)
    out_path = Path(outpath)

    if not cif_path.is_dir():
        raise ValueError(f"CIF directory does not exist: {cif_dir}")

    cif_files = sorted(cif_path.glob("*.cif"))
    if not cif_files:
        raise ValueError(f"No .cif files found in {cif_dir}")

    manifest = []
    with ThreadPoolExecutor(max_workers=max_workers) as pool:
        futures = [
            pool.submit(
                _setup_single_cif,
                cif,
                out_path,
                adsorbates,
                temperatures,
                pressures,
                cutoff,
                n_cycle,
                template_dir,
                model_path,
                model_type,
                E_comps,
                task,
                mode,
                save_poscar,
            )
            for cif in cif_files
        ]
        for future in futures:
            manifest.extend(future.result())

    manifest_path = out_path / "simulations.jsonl"
    with manifest_path.open("w") as f:
        for entry in manifest:
            f.write(json.dumps(entry) + "\n")

    rename_map = {
        entry["original_cif_stem"]: entry["safe_cif_stem"]
        for entry in manifest
        if "original_cif_stem" in entry
    }
    if rename_map:
        _write_cif_mapping(out_path, rename_map)

    return manifest


def _write_cif_mapping(out_path: Path, mapping: dict[str, str]) -> None:
    """Write/merge {original_stem: safe_stem} to ``cif_mapping.json``."""
    mapping_path = out_path / "cif_mapping.json"
    existing: dict[str, str] = {}
    if mapping_path.exists():
        existing = json.loads(mapping_path.read_text())
    existing.update(mapping)
    mapping_path.write_text(json.dumps(existing, indent=2, sort_keys=True))


def compute_ecomp(
    adsorbate_def: str,
    model_path: str,
    model_type: str,
    *,
    task: str | None = None,
    device: str = "cuda",
    cache_path: str | None = None,
) -> float:
    """Compute E_comp (ML energy of one isolated rigid adsorbate molecule).

    Wraps :func:`pygRASPA.utils.read_molecule` and
    :func:`pygRASPA.ml_setup.setup_calculator`. Used to obtain the per-
    component reference energy that pygRASPA requires for the Metropolis
    criterion. Results may be cached to a JSON file so repeated isotherm
    sweeps with the same model/adsorbate avoid recomputation.

    Args:
        adsorbate_def: Path to a gRASPA ``*.def`` molecule file.
        model_path: ML model checkpoint path.
        model_type: pygRASPA model-type identifier.
        task: Task name (required for FAIRChem-uma / FAIRChem-AllScAIP).
        device: ``"cuda"`` or ``"cpu"``.
        cache_path: Optional JSON file for memoizing results keyed by
            ``(model_path, model_type, task, adsorbate stem)``.

    Returns:
        E_comp in eV.

    Raises:
        ImportError: If pygRASPA is not installed.
        FileNotFoundError: If ``adsorbate_def`` does not exist.
    """
    def_path = Path(adsorbate_def)
    if not def_path.exists():
        raise FileNotFoundError(
            f"Adsorbate def file not found: {adsorbate_def}"
        )

    cache_key = f"{model_path}|{model_type}|{task or ''}|{def_path.stem}"
    if cache_path is not None:
        cp = Path(cache_path)
        if cp.exists():
            cache = json.loads(cp.read_text())
            if cache_key in cache:
                return float(cache[cache_key])

    try:
        from pygRASPA.ml_setup import setup_calculator
        from pygRASPA.utils import read_molecule
    except ImportError as e:
        raise ImportError(
            "pygRASPA is required for compute_ecomp. "
            "Install pygRASPA on the GPU machine first."
        ) from e

    atoms = read_molecule(str(def_path))
    atoms.info = {"charge": 0, "spin": 1}
    atoms.calc = setup_calculator(
        model_path, device, model_type=model_type, task=task
    )
    value = float(atoms.get_potential_energy())

    if cache_path is not None:
        cp = Path(cache_path)
        cache = json.loads(cp.read_text()) if cp.exists() else {}
        cache[cache_key] = value
        cp.write_text(json.dumps(cache, indent=2, sort_keys=True))

    return value


def _convert_uptake(
    molecules_per_uc: float,
    error_per_uc: float,
    cif_path: str,
    n_uc: tuple[int, int, int],
    unit: str,
    molar_mass: float | None = None,
) -> tuple[float, float]:
    """Convert molecules-per-supercell to a chemistry-friendly uptake unit.

    Args:
        molecules_per_uc: Mean adsorbed molecule count over the full
            ``n_uc`` supercell.
        error_per_uc: Standard error on the same scale.
        cif_path: Path to the framework CIF (used for mass / volume).
        n_uc: ``(uc_x, uc_y, uc_z)`` replication factors.
        unit: ``"mol/kg"``, ``"mg/g"``, or ``"g/L"``.
        molar_mass: Adsorbate molar mass (g/mol), required for ``mg/g``
            and ``g/L``.

    Returns:
        ``(uptake, error)`` in the requested unit.
    """
    atoms = ase_read(cif_path)
    n_cells = n_uc[0] * n_uc[1] * n_uc[2]
    framework_mass = sum(atoms.get_masses()) * n_cells  # g/mol
    if unit == "mol/kg":
        return (
            molecules_per_uc / framework_mass * 1000,
            error_per_uc / framework_mass * 1000,
        )
    if molar_mass is None:
        raise ValueError(f"molar_mass is required for unit={unit!r}")
    if unit == "mg/g":
        return (
            molecules_per_uc * molar_mass / framework_mass * 1000,
            error_per_uc * molar_mass / framework_mass * 1000,
        )
    if unit == "g/L":
        vol_l = atoms.get_volume() * n_cells * 1e-27
        return (
            molecules_per_uc / 6.022e23 * molar_mass / vol_l,
            error_per_uc / 6.022e23 * molar_mass / vol_l,
        )
    raise ValueError(f"Unsupported unit: {unit!r}")


_MOLAR_MASS = {
    "CO2": 44.0098,
    "N2": 28.0134,
    "H2": 2.01588,
    "CH4": 16.0425,
    "methane": 16.0425,
    "H2O": 18.0153,
    "TIP4P": 18.0153,
    "SO2": 64.066,
    "Xe": 131.293,
    "Kr": 83.798,
}


def get_output_data(
    output_path: str,
    *,
    unit: str = "mol/kg",
    output_fname: str = "output.log",
    n_skip_cycles: int | None = None,
    cifname: str | None = None,
) -> dict:
    """Parse a pygRASPA per-cycle JSON-lines log and average uptake.

    pygRASPA writes one JSON object per Monte Carlo cycle to the log file
    specified via ``log_file_path`` (``run`` mode) or ``log_file``
    (``run-auto`` mode). Each line is expected to carry the current cycle
    index and per-component molecule counts.

    The exact field names vary across pygRASPA versions; this parser is
    tolerant and looks for the first plausible key in each category
    (``cycle``/``step``/``i_cycle`` for the index;
    ``molecules``/``N_components``/``N`` for counts). If the schema in your
    log differs, raise an issue and pass the field names through
    pygRASPA's own ``readCycles``/utils helpers.

    Args:
        output_path: Directory containing the simulation output.
        unit: ``"mol/kg"``, ``"mg/g"``, or ``"g/L"``.
        output_fname: Log filename (default ``output.log``).
        n_skip_cycles: Number of leading cycles to drop. Defaults to
            ``NumberOfInitializationCycles + NumberOfEquilibrationCycles``
            from ``simulation.input``.
        cifname: Framework CIF name in ``output_path``. Auto-detected if
            ``None``.

    Returns:
        Dict with keys: ``success``, ``uptake`` (per-component list),
        ``error`` (per-component list), ``unit``, ``n_components``,
        ``n_production_cycles``.

    Raises:
        ValueError: If the log cannot be parsed or required metadata is
            missing.
    """
    output_dir = Path(output_path)
    log_path = output_dir / output_fname
    if not log_path.exists():
        raise ValueError(f"Output log not found: {log_path}")

    cycle_keys = ("cycle", "step", "i_cycle", "Cycle")
    count_keys = ("molecules", "N_components", "N", "n_molecules")

    cycle_records: list[tuple[int, list[float]]] = []
    with log_path.open() as fh:
        for raw in fh:
            raw = raw.strip()
            if not raw or not raw.startswith("{"):
                continue
            try:
                rec = json.loads(raw)
            except json.JSONDecodeError:
                continue
            cycle = next((rec[k] for k in cycle_keys if k in rec), None)
            counts = next((rec[k] for k in count_keys if k in rec), None)
            if cycle is None or counts is None:
                continue
            if isinstance(counts, (int, float)):
                counts = [float(counts)]
            else:
                counts = [float(c) for c in counts]
            cycle_records.append((int(cycle), counts))

    if not cycle_records:
        raise ValueError(
            f"No parseable cycle records in {log_path}. "
            "Confirm the file is the pygRASPA JSON-lines log."
        )

    if n_skip_cycles is None:
        sim_input = output_dir / "simulation.input"
        n_skip_cycles = (
            _read_skip_cycles(sim_input) if sim_input.exists() else 0
        )

    production = [c for c in cycle_records if c[0] >= n_skip_cycles]
    if not production:
        raise ValueError(
            f"No cycles >= n_skip_cycles={n_skip_cycles} in {log_path}"
        )

    n_components = len(production[0][1])
    sums = [0.0] * n_components
    sq_sums = [0.0] * n_components
    for _, counts in production:
        if len(counts) != n_components:
            raise ValueError(
                "Inconsistent component count across cycles "
                f"({n_components} vs {len(counts)})"
            )
        for i, v in enumerate(counts):
            sums[i] += v
            sq_sums[i] += v * v
    n = len(production)
    means = [s / n for s in sums]
    variances = [max(0.0, sq / n - m * m) for sq, m in zip(sq_sums, means)]
    sems = [(v / n) ** 0.5 for v in variances]

    # Read unit cell replication from simulation.input.
    n_uc = _read_unit_cells(output_dir / "simulation.input")

    if cifname is None:
        cifs = list(output_dir.glob("*.cif"))
        if len(cifs) != 1:
            raise ValueError(
                f"Found {len(cifs)} CIFs in {output_path}; pass cifname."
            )
        cif_path = str(cifs[0])
    else:
        cif_path = str(output_dir / cifname)

    uptakes: list[float] = []
    errors: list[float] = []
    for i in range(n_components):
        molar_mass = None
        if unit in ("mg/g", "g/L"):
            ads = _component_name_from_input(output_dir / "simulation.input", i)
            molar_mass = _MOLAR_MASS.get(ads)
            if molar_mass is None:
                raise ValueError(
                    f"No molar mass for component {i} ({ads!r}); "
                    "extend _MOLAR_MASS or request mol/kg."
                )
        u, e = _convert_uptake(
            means[i], sems[i], cif_path, n_uc, unit, molar_mass
        )
        uptakes.append(u)
        errors.append(e)

    return {
        "success": True,
        "uptake": uptakes if n_components > 1 else uptakes[0],
        "error": errors if n_components > 1 else errors[0],
        "unit": unit,
        "n_components": n_components,
        "n_production_cycles": n,
    }


def _read_skip_cycles(sim_input: Path) -> int:
    init = equil = 0
    for line in sim_input.read_text().splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[0] == "NumberOfInitializationCycles":
            init = int(parts[1])
        elif len(parts) >= 2 and parts[0] == "NumberOfEquilibrationCycles":
            equil = int(parts[1])
    return init + equil


def _read_unit_cells(sim_input: Path) -> tuple[int, int, int]:
    for line in sim_input.read_text().splitlines():
        parts = line.split()
        if parts and parts[0] == "UnitCells" and len(parts) >= 5:
            # "UnitCells 0 ux uy uz" (box_index ux uy uz)
            return int(parts[2]), int(parts[3]), int(parts[4])
    return 1, 1, 1


def _component_name_from_input(sim_input: Path, index: int) -> str | None:
    """Return the MoleculeName for component *index* in simulation.input."""
    if not sim_input.exists():
        return None
    for line in sim_input.read_text().splitlines():
        parts = line.split()
        if (
            len(parts) >= 4
            and parts[0] == "Component"
            and parts[1] == str(index)
            and parts[2] == "MoleculeName"
        ):
            return parts[3]
    return None
